label: 'Neue Mitglieder'
display:
  default:
    display_title: Master
    display_options:
      exposed_form:
        options:
          submit_button: Anwenden
          reset_button_label: Zurücksetzen
          exposed_sorts_label: 'Sortieren nach'
          sort_asc_label: Aufsteigend
          sort_desc_label: Absteigend
      title: 'Neue Mitglieder'
  block_1:
    display_title: 'Neue Mitglieder'
    display_options:
      block_description: 'Neue Mitglieder'
      block_category: Benutzer
