display:
  default:
    display_title: Master
    display_options:
      exposed_form:
        options:
          submit_button: Filter
          reset_button_label: Zurücksetzen
          exposed_sorts_label: 'Sortieren nach'
          sort_asc_label: Aufsteigend
          sort_desc_label: Absteigend
      pager:
        options:
          expose:
            items_per_page_label: 'Elemente pro Seite'
            items_per_page_options_all_label: '- Alle -'
            offset_label: Offset
          tags:
            previous: ‹‹
            next: ››
      fields:
        path:
          label: Pfad
        count:
          label: Anzahl
        timestamp:
          label: 'Letzter Zugriff'
        langcode:
          label: Sprache
        redirect_404_operations:
          label: Operationen
      filters:
        path:
          expose:
            label: Pfad
        langcode:
          expose:
            label: Sprache
  page_1:
    display_title: Seite
