<?php

/**
 * @file
 * Layout manager - Set width and appearance related settings.
 */

use Drupal\Core\Entity\Display\EntityViewDisplayInterface;
use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Entity\FieldableEntityInterface;
use Drupal\jamden_layout\Plugin\Field\FieldType\LayoutItem;

/**
 * Implements hook_entity_view_alter().
 */
function jamden_layout_entity_view_alter(array &$build, EntityInterface $entity, EntityViewDisplayInterface $display) {
  static $spans = 0;

  // We're looking for an entity with fields.
  if (!$entity instanceof FieldableEntityInterface) {
    return;
  }

  foreach ($entity->getFields() as $field) {
    $item = $field->first();

    if ($item instanceof LayoutItem) {
      // Add column width class.
      if ($item->width) {

        // Fallback class.
        $span_class = 'span-default';

        // First element in new "row".
        if ($spans == 0) {
          $build['#attributes']['class'][] = 'clear';
        }

        // Total spans in "row".
        $spans = ((int) $item->width) + $spans;

        if ($spans > 8) {
          if ($spans > 12) {
            $build['#attributes']['class'][] = 'clear';
          }
          else {
            // We know if total spans is bigger than 8 the next
            // span will not fit.
            $build['#attributes']['class'][] = 'span-break';
          }
          // Reset total spans i row.
          $spans = 0;
        }

        // If spans is not the default, we set the span class.
        if ($item->width !== '0') {
          $span_class = 'span-' . $item->width;
        }
      }
      else {
        // Fallback.
        $spans = 0;
        $span_class = 'span-default';
      }

      // Finally we add the spann class to the attributes array.
      $build['#attributes']['class'][] = $span_class;

      // Add clear class if present.
      if ($item->clear) {
        $build['#attributes']['class'][] = 'clear';
      }

      // Align to right if present.
      if ($item->float) {
        $build['#attributes']['class'][] = 'span-align-right';
      }

      // Always add layout-item class so we can target them specifically.
      $build['#attributes']['class'][] = 'layout-item';
    }
  }
}
