version: 2
updates:
- package-ecosystem: composer
  directory: "/drupal"
  schedule:
    interval: daily
    time: '04:00'
  open-pull-requests-limit: 10
# We're disabling dependabot updates until we have time to do a full update and
# get into sync - otherwise we'll have a lot more open PRs than we're willing
# to handle in one go.
# - package-ecosystem: github-actions
#   directory: "/"
#   schedule:
#     interval: daily
#     time: '04:00'
#   open-pull-requests-limit: 10
# - package-ecosystem: npm
#   directory: "/drupal/web/themes/custom/camp"
#   schedule:
#     interval: daily
#     time: '04:00'
#   open-pull-requests-limit: 10
# - package-ecosystem: npm
#   directory: "/api"
#   schedule:
#     interval: daily
#     time: '04:00'
#   open-pull-requests-limit: 10
# - package-ecosystem: npm
#   directory: "/drupal/apps/jobs"
#   schedule:
#     interval: daily
#     time: '04:00'
#   open-pull-requests-limit: 10
