features:
  node_user_picture: 1
  comment_user_picture: 1
  comment_user_verification: 1
  favicon: 1
logo:
  use_default: 0
  path: ''
favicon:
  use_default: 0
  path: themes/custom/camp/images/sl_fav.png
  mimetype: image/png
image_path: ''
image_upload: ''
default_teaser_image: ''
default_teaser_image_path: ''
countdown_enabled: '1'
countdown_date: 'July 22, 2022 08:00:00'
