# https://taskfile.dev
version: 3

tasks:
  getdb:
    desc: "Fetch database dump"
    cmds:
      - rm -fr docker/db/fetch
      - mkdir -p docker/db/fetch
      - platform db:dump -e {{.ENV}} --gzip -d docker/db/fetch
      - rm -f docker/db/initdb.d/*.gz
      - mv docker/db/fetch/* docker/db/initdb.d/
      - rm -fr docker/db/fetch
    vars:
      ENV: '{{.ENV | default "master"}}'

  reset:
    desc: "Reset docker-environment and bring site back up"
    cmds:
      - scripts/docker-reset.sh

  down:
    desc: "Take down a running site removing any state"
    cmds:
      - docker-compose kill
      - docker-compose rm -v -f
      - docker-compose down --remove-orphans -v
