# https://taskfile.dev
version: 3

tasks:
  drupal:getdb:
    desc: "Fetch database dump"
    dir: drupal
    cmds:
      - rm -fr docker/db/fetch
      - mkdir -p docker/db/fetch
      - platform db:dump -e {{.ENV}} --app drupal -p kigwipdp3tsiq --gzip -d docker/db/fetch
      - rm -f docker/db/initdb.d/*.gz
      - mkdir -p docker/db/initdb.d/
      - mv docker/db/fetch/* docker/db/initdb.d/
      - rm -fr docker/db/fetch
    vars:
      ENV: '{{.ENV | default "master"}}'

  api:reset:
    desc: "Reset docker-environment and bring api back up"
    dir: api
    cmds:
      - yarn install
      - yarn start:dev

  apps:build:
    desc: "BUilds all apps"
    dir: drupal/apps/jobs
    cmds:
      - yarn install
      - yarn build

  drupal:reset:
    desc: "Reset docker-environment and bring site back up"
    dir: drupal
    cmds:
      - scripts/docker-reset.sh

  drupal:upgrade:core:
    desc: "Reset docker-environment and bring site back up"
    summary: |
      Assumes docker-compose is up and running
    dir: drupal
    cmds:
      - scripts/upgrade-core.sh
    preconditions:
      - sh: "docker compose ps php -q > /dev/null"
        msg: "Could not detect running php container"

  drupal:upgrade:status:
    desc: "Get a status for updatable composer packages"
    summary: |
      Assumes docker-compose is up and running
    dir: drupal
    cmds:
      - docker compose exec php bash -c "cd .. && composer outdated"
    preconditions:
      - sh: "docker compose ps php -q > /dev/null"
        msg: "Could not detect running php container"

  drupal:up:
    desc: "Start Drupal site containers"
    dir: drupal
    cmds:
      - docker compose up --remove-orphans -d

  drupal:down:
    desc: "Take down a running site removing any state"
    dir: drupal
    cmds:
      - docker compose kill
      - docker compose rm -v -f
      - docker compose down --remove-orphans -v
