<?php

/**
 * @file
 * Theme-hook for Card Gallery.
 */

use Drupal\file_entity\Entity\FileEntity;

/**
 * Implements hook_theme().
 */
function card_gallery_theme() {
  return [
    'card_gallery_formatter' => [
      'variables' => [
        'items' => [],
      ],
    ],
  ];
}

/**
 * Implements template_preprocess_image_title_caption_formatter().
 */
function template_preprocess_card_gallery_formatter(&$variables) {

  $meta_data = [];

  // Add caption and credits to variables.
  foreach ($variables['items'] as $delta => &$image_item) {
    $image_entity = $image_item['#item']->entity;
    $meta_data[$delta]['credits'] = card_gallery_translated_credits_from_image($image_entity);
    $meta_data[$delta]['caption'] = $image_entity->field_image_caption->value;
  }

  $variables['meta_data'] = $meta_data;
}

/**
 * Generate the proper credits string from an image file-entity.
 *
 * @param FileEntity $image
 *   Instansiated image.
 *
 * @return string
 *   Translated credits string
 */
function card_gallery_translated_credits_from_image(FileEntity $image) {

  // Return empty string if there is no credits.
  if (empty($image->field_image_credits->value)) {
    return '';
  }

  return (string) t(
    'Photo: @credits',
    ['@credits' => $image->field_image_credits->value]
  );
}
