<?php

/**
 * @file
 * Theme-hook for Card Gallery.
 */

/**
 * Implements hook_theme().
 */
function card_gallery_theme() {
  return [
    'card_gallery_formatter' => [
      'variables' => [
        'items' => [],
      ],
    ],
  ];
}

/**
 * Implements template_preprocess_image_title_caption_formatter().
 */
function template_preprocess_card_gallery_formatter(&$variables) {

  $meta_data = [];

  // Add caption and credits to variables.
  foreach ($variables['items'] as $delta => &$image_item) {
    $image_entity = $image_item['#item']->entity;
    $meta_data[$delta]['credits'] = jamden_base_translated_credits_from_image($image_entity);
    $meta_data[$delta]['caption'] = $image_entity->field_image_caption->value;
  }

  $variables['meta_data'] = $meta_data;
}
