features:
  node_user_picture: 1
  comment_user_picture: 1
  comment_user_verification: 1
  favicon: 1
logo:
  use_default: 0
  path: ''
favicon:
  use_default: 1
image_path: ''
image_upload: ''
default_teaser_image: ''
default_teaser_image_path: ''
