module:
  admin_toolbar: 0
  automated_cron: 0
  block: 0
  block_content: 0
  breakpoint: 0
  ckeditor: 0
  color: 0
  comment: 0
  config: 0
  contact: 0
  contextual: 0
  datetime: 0
  dblog: 0
  dynamic_page_cache: 0
  editor: 0
  entity_reference_revisions: 0
  field: 0
  field_ui: 0
  file: 0
  file_entity: 0
  filter: 0
  help: 0
  history: 0
  image: 0
  jamden_top_image: 0
  language: 0
  link: 0
  locale: 0
  menu_ui: 0
  multilingual_frontpage: 0
  node: 0
  options: 0
  page_cache: 0
  paragraphs: 0
  paragraphs_type_permissions: 0
  path: 0
  purge: 0
  purge_drush: 0
  purge_processor_cron: 0
  purge_purger_http: 0
  purge_queuer_coretags: 0
  purge_tokens: 0
  purge_ui: 0
  rdf: 0
  responsive_image: 0
  search: 0
  shortcut: 0
  stage_file_proxy: 0
  system: 0
  taxonomy: 0
  text: 0
  toolbar: 0
  tour: 0
  update: 0
  user: 0
  video_embed_field: 0
  views_ui: 0
  menu_link_content: 1
  views: 10
  standard: 1000
theme:
  stable: 0
  classy: 0
  bartik: 0
  seven: 0
  camp: 0
_core:
  default_config_hash: m2GVq11UAOVuNgj8x0t5fMOPujpvQQ_zxLoaly1BMEU
langcode: en
