session:
  parameter: language
url:
  source: path_prefix
  prefixes:
    en: en
    '': null
  domains:
    en: ''
selected_langcode: da
_core:
  default_config_hash: uEePITI9tV6WqzmsTb7MfPCi5yPWXSxAN1xeLcYFQbM
langcode: da
