session:
  parameter: language
url:
  source: path_prefix
  prefixes:
    en: en
    '': null
    da: da
  domains:
    en: ''
    da: ''
selected_langcode: en
_core:
  default_config_hash: uEePITI9tV6WqzmsTb7MfPCi5yPWXSxAN1xeLcYFQbM
langcode: en
