purgers:
  -
    order_index: 1
    instance_id: f26d5a05c9
    plugin_id: http
processors: {  }
queuers: {  }
queue: database
_core:
  default_config_hash: zszQgrpbU_SwoV7zSROlOcgRTndttz24blQTCXuJlUU
langcode: da
