display:
  default:
    display_title: Master
    display_options:
      exposed_form:
        options:
          submit_button: Filter
          reset_button_label: Gendan
          exposed_sorts_label: 'Sortér efter'
          sort_asc_label: Stigende
          sort_desc_label: Faldende
      pager:
        options:
          expose:
            items_per_page_label: 'Antal elementer'
            items_per_page_options_all_label: '- Alle -'
            offset_label: Forskydning
          tags:
            previous: ‹‹
            next: ››
      fields:
        path:
          label: Sti
        count:
          label: Antal
        timestamp:
          label: 'Sidste tilgået'
        langcode:
          label: Sprog
        redirect_404_operations:
          label: Handlinger
      filters:
        path:
          expose:
            label: Sti
        langcode:
          expose:
            label: Sprog
      title: 'Fix 404-sider'
  page_1:
    display_title: Side
