<?php

/**
 * @file
 * Jamden Juicebox - alters juicebox settings and views.
 */

use Drupal\Core\Entity\Display\EntityViewDisplayInterface;
use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Entity\FieldableEntityInterface;
use Drupal\file\Plugin\Field\FieldType\FileFieldItemList;
use Drupal\juicebox\JuiceboxGallery;

/**
 * Implements hook_juicebox_gallery_data_alter().
 */
function jamden_juicebox_juicebox_gallery_alter(JuiceboxGallery $juicebox, FileFieldItemList $data) {

  $juicebox_images = $juicebox->getImages();

  foreach ($data as $key => $field) {

    $image_entity = $field->entity;
    $image = $juicebox_images[$key];

    if ($image_entity->field_image_caption) {
      $image['caption'] = $image_entity->field_image_caption->value;
    }

    if ($image_entity->field_image_credits) {
      $image['title'] = jamden_juicebox_translated_credits_from_image($image_entity);
    }

    $juicebox->updateImage($key, $image['src_data'], $image['title'], $image['caption']);
  }
}

/**
 * Generate the proper credits string from an image file-entity.
 *
 * @param FileEntity $image
 *   Instansiated image.
 *
 * @return string
 *   Translated credits string
 */
function jamden_juicebox_translated_credits_from_image($image) {

  // Return empty string if there is no credits.
  if (empty($image->field_image_credits->value)) {
    return '';
  }

  return (string) t(
    'Photo: @credits',
    ['@credits' => $image->field_image_credits->value]
  );
}
